version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: selflearning-interoperability
    restart: always
    ports: 
      - 1972:1972
      - 52773:52773
      - 53773
    volumes:
      - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./src:/irisdev/src